** part 1 **

# import library

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
lis=[1,2,3,4]
print(lis)

[1, 2, 3, 4]

** series **

In [5]:
s=pd.Series(lis)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
type(s)

pandas.core.series.Series

In [8]:
empty=pd.Series([])
print(empty)

Series([], dtype: object)

In [9]:
empty=pd.Series([])
empty

Series([], dtype: object)

** customize index number **

In [11]:
a=pd.Series(['a','b','c','d','e'],index=[1,2,3,4,5])
print(a)

1    a
2    b
3    c
4    d
5    e
dtype: object

** given name to the series **

In [3]:
a=pd.Series(['a','b','c','d','e'],index=[1,2,3,4,5],name='demo')
print(a)

1    a
2    b
3    c
4    d
5    e
Name: demo, dtype: object

** scalar series **

In [4]:
s_series=pd.Series(0.5)
print(s_series)

0    0.5
dtype: float64

In [6]:
s_series=pd.Series((0.5),index=[3,4])
print(s_series)

3    0.5
4    0.5
dtype: float64

** Pandas Series with Dictionary **

In [7]:
dict_series=pd.Series({'p':2,'q':3,'r':5})
print(dict_series)

p    2
q    3
r    5
dtype: int64

In [8]:
dict_series[0]

C:\Users\Athira\AppData\Local\Temp\ipykernel_2348\1198263229.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dict_series[0]

np.int64(2)

In [10]:
dict_series[1:3]

q    3
r    5
dtype: int64

In [11]:
max(dict_series)

5

In [12]:
min(dict_series)

2

In [13]:
dict_series=pd.Series({'p':[1,2,3],'q':[7,8,9],'r':[4,5,6]})
print(dict_series)

p    [1, 2, 3]
q    [7, 8, 9]
r    [4, 5, 6]
dtype: object

------------ PART 2 -------------------

** pandas data frame **

In [14]:
import pandas as pd

In [ ]:
Data Frame
In Pandas, a DataFrame is a two-dimensional, labeled data structure that resembles a spreadsheet or 
SQL table. It consists of rows and columns, where each column can have a different data type.

In [16]:
df=pd.DataFrame()
print(pd)

<module 'pandas' from 'C:\\Users\\Athira\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

** DataFrame using List **

In [17]:
lst=[2,3,4,5,6]
df=pd.DataFrame(lst)
print(df)

   0
0  2
1  3
2  4
3  5
4  6

0 is column name

In [18]:
lst=[[2,3,4,5,6],[4,5,6,7,8]]
df=pd.DataFrame(lst)
print(df)

   0  1  2  3  4
0  2  3  4  5  6
1  4  5  6  7  8

In [19]:
lst=[[2,3,4,5,6],[4,5,6,7,8],[6,7,8,9,0]]
df=pd.DataFrame(lst)
print(df)

   0  1  2  3  4
0  2  3  4  5  6
1  4  5  6  7  8
2  6  7  8  9  0

In [21]:
dic=[{'a':1,'b':2,'c':3},{'a':1,'b':2,'c':3}]
df=pd.DataFrame(dic)
print(df)

   a  b  c
0  1  2  3
1  1  2  3

In [ ]:
a,b,c is a column name (table header), i.e, dictionary key is column name

In [22]:
dict2=[{'name':['anu','manu','anju'],'roll no':[1,3,4]}]
df=pd.DataFrame(dict2)
df

                name    roll no
0  [anu, manu, anju]  [1, 3, 4]

In [23]:
dict2=[{'name':['anu','manu','anju']},{'roll no':[1,3,4]}]
df=pd.DataFrame(dict2)
df

                name    roll no
0  [anu, manu, anju]        NaN
1                NaN  [1, 3, 4]

In [27]:
dict2={'name':pd.Series(['anu','manu','anju']),'roll no':pd.Series([1,3,4])}
df=pd.DataFrame(dict2)
df

   name  roll no
0   anu        1
1  manu        3
2  anju        4

In [ ]:
using series add values in first column

In [ ]:
** Read CSV(Common Separated Values) as DataFrame **

In [29]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\annual-enterprise-survey-2024-financial-year-provisional.csv")
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
read_csv is used for reading a file

In [31]:
type(df)

pandas.core.frame.DataFrame

--------------- part 3 ----------------------------

** Data Frame Functions **

In [32]:
import pandas as pd

In [33]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\annual-enterprise-survey-2024-financial-year-provisional.csv")

In [34]:
df.columns   # used for getting column name only

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [35]:
df.shape  # no.of rows (55620) and columns (10)

(55620, 10)

In [36]:
df.size    # (rows * column)

556200

In [37]:
df.head   # first 5 rows ( it is mainly used for how to look like)

<bound method NDFrame.head of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]>

In [38]:
 df.head(2)   # first 2 rows

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...

In [39]:
df.tail  # last 5 rows

<bound method NDFrame.tail of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]>

In [40]:
df.tail(3)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [41]:
df.describe

<bound method NDFrame.describe of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]>

In [46]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\currency.csv")
df

    Code Symbol                      Name
0    AED    د.إ    United Arab Emirates d
1    AFN      ؋            Afghan afghani
2    ALL      L              Albanian lek
3    AMD    AMD             Armenian dram
4    ANG      ƒ  Netherlands Antillean gu
..   ...    ...                       ...
158  XOF    CFA    West African CFA franc
159  XPF     Fr                 CFP franc
160  YER      ﷼               Yemeni rial
161  ZAR      R        South African rand
162  ZMW     ZK            Zambian kwacha

[163 rows x 3 columns]

In [48]:
df.describe()  # used for describing values basic mathematical functions

       Code Symbol                    Name
count   163    163                     163
unique  163    107                     163
top     AED      $  United Arab Emirates d
freq      1     28                       1

In [49]:
df.info() # basic idea of a database

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Code    163 non-null    object
 1   Symbol  163 non-null    object
 2   Name    163 non-null    object
dtypes: object(3)
memory usage: 3.9+ KB

In [50]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\archive\world_top_restaurants_dataset.csv")

In [51]:
df

,Restaurant_Name,City,Country,Cuisine_Type,Michelin_Stars,Average_Price_USD,Chef,Established_Year,Seating_Capacity,Rating,Signature_Dish,Years_Operating,Price_Category,Star_Category,Continent
0,Osteria Francescana,Modena,Italy,Italian Contemporary,3,320,Massimo Bottura,1995,28,4.9,Five Ages of Parmigiano,30,Luxury,Three Stars,Europe
1,Odette,Singapore,Singapore,French Contemporary,3,320,Julien Royer,2008,32,4.9,Hokkaido Sea Urchin,17,Luxury,Three Stars,Asia
2,The French Laundry,Yountville,USA,French,3,390,Thomas Keller,1994,60,4.9,Oysters and Pearls,31,Luxury,Three Stars,North America
3,Arpège,Paris,France,French Vegetarian,3,425,Alain Passard,1986,40,4.9,Heirloom Tomatoes,39,Ultra-Luxury,Three Stars,Europe
4,Mirazur,Menton,France,Mediterranean,3,350,Mauro Colagreco,1991,36,4.8,Salt Crusted Beetroot,34,Luxury,Three Stars,Europe
5,Frantzén,Stockholm,Sweden,Nordic Contemporary,3,380,Björn Frantzén,2008,23,4.8,Reindeer Moss,17,Luxury,Three Stars,Europe
6,Le Bernardin,New York,USA,French Seafood,3,295,Eric Ripert,1972,62,4.8,Barely Cooked Salmon,53,Luxury,Three Stars,North America
7,Piazza Duomo,Alba,Italy,Italian,3,310,Enrico Crippa,2005,35,4.8,Fassona Beef,20,Luxury,Three Stars,Europe
8,Arzak,San Sebastián,Spain,Basque,3,295,Juan Mari Arzak,1897,50,4.8,Red Mullet,128,Luxury,Three Stars,Europe
9,Atelier Crenn,San Francisco,USA,Contemporary French,3,345,Dominique Crenn,2011,50,4.8,Kir Breton Royale,14,Luxury,Three Stars,North America
10,Benu,San Francisco,USA,Contemporary American,3,298,Corey Lee,2010,56,4.8,Thousand Year Quail Egg,15,Luxury,Three Stars,North America
11,Alléno Paris,Paris,France,French Haute Cuisine,3,385,Yannick Alléno,2003,55,4.8,Cabbage & Caviar,22,Luxury,Three Stars,Europe
12,La Pergola,Rome,Italy,Italian Haute Cuisine,3,310,Heinz Beck,1994,50,4.8,Fagottelli,31,Luxury,Three Stars,Europe
13,Quique Dacosta,Dénia,Spain,Mediterranean,3,270,Quique Dacosta,1989,48,4.8,Rice with Seafood,36,Luxury,Three Stars,Europe
14,L'Astrance,Paris,France,French Contemporary,3,305,Pascal Barbot,2000,25,4.8,Lobster Ravioli,25,Luxury,Three Stars,Europe
15,El Celler de Can Roca,Girona,Spain,Contemporary Catalan,3,280,Joan Roca,1986,45,4.7,El Mundo,39,Luxury,Three Stars,Europe
16,Geranium,Copenhagen,Denmark,New Nordic,3,420,Rasmus Kofoed,2007,40,4.7,Radish & Roses,18,Ultra-Luxury,Three Stars,Europe
17,Eleven Madison Park,New York,USA,Contemporary American,3,365,Daniel Humm,1998,80,4.7,Lavender Honey Duck,27,Luxury,Three Stars,North America
18,Alinea,Chicago,USA,Molecular Gastronomy,3,385,Grant Achatz,2005,64,4.7,Black Truffle Explosion,20,Luxury,Three Stars,North America
19,Le Calandre,Rubano,Italy,Italian,3,290,Massimiliano Alajmo,1981,50,4.7,Risotto,44,Luxury,Three Stars,Europe
20,Azurmendi,Larrabetzu,Spain,Basque,3,265,Eneko Atxa,2005,45,4.7,Roasted Egg,20,Luxury,Three Stars,Europe
21,Ultraviolet,Shanghai,China,Avant-garde,3,570,Paul Pairet,2012,10,4.6,20 Textures,13,Ultra-Luxury,Three Stars,Asia
22,Noma,Copenhagen,Denmark,New Nordic,2,450,René Redzepi,2003,40,4.8,Fermented Vegetables,22,Ultra-Luxury,Two Stars,Europe
23,Den,Tokyo,Japan,Japanese Kaiseki,2,280,Zaiyu Hasegawa,2007,26,4.7,Dentucky Fried Chicken,18,Luxury,Two Stars,Asia
24,SingleThread,Healdsburg,USA,Japanese-Californian,2,325,Kyle & Katina Connaughton,2016,48,4.7,Whole Roasted Chicken,9,Luxury,Two Stars,North America
25,Restaurant Tim Raue,Berlin,Germany,Asian Fusion,2,245,Tim Raue,2010,48,4.7,Char Sui Duck,15,Premium,Two Stars,Europe
26,Narisawa,Tokyo,Japan,Japanese Innovative,2,275,Yoshihiro Narisawa,2003,36,4.7,Satoyama Cuisine,22,Luxury,Two Stars,Asia
27,Florilège,Tokyo,Japan,French Contemporary,2,235,Hiroyasu Kawate,2009,28,4.7,Ayu Fish,16,Premium,Two Stars,Asia
28,Steirereck,Vienna,Austria,Austrian Contemporary,2,265,Heinz Reitbauer,2005,60,4.7,Char with Hay,20,Luxury,Two Stars,Europe
29,Momofuku Ko,New York,USA,Contemporary American,2,285,Sean Gray,2008,12,4.7,Shaved Foie Gras,17,Luxury,Two Stars,North America
30,Restaurant André,Singapore,Singapore,Asian Fusion,2,285,André Chiang,2010,30,4.7,Octopus,15,Luxury,Two Stars,Asia
31,Amber,Hong Kong,Hong Kong,French,2,245,Richard Ekkebus,2005,46,4.7,Langoustine,20,Premium,Two Stars,Asia
32,Disfrutar,Barcelona,Spain,Mediterranean,2,250,Oriol Castro,2014,52,4.6,Panchino,11,Luxury,Two Stars,Europe
33,Mugaritz,Errenteria,Spain,Basque Experimental,2,275,Andoni Luis Aduriz,1998,20,4.6,Edible Stones,27,Luxury,Two Stars,Europe
34,Alchemist,Copenhagen,Denmark,Experimental,2,550,Rasmus Munk,2015,50,4.5,Dehydrated Malt Flatbread,10,Ultra-Luxury,Two Stars,Europe
35,Asador Etxebarri,Axpe,Spain,Basque Grill,1,210,Victor Arguinzoniz,1990,30,4.7,Grilled Turbot,35,Premium,One Star,Europe
36,The Clove Club,London,UK,British Contemporary,1,165,Isaac McHale,2013,40,4.6,Buttermilk Chicken,12,Premium,One Star,Europe
37,Burnt Ends,Singapore,Singapore,Modern BBQ,1,165,Dave Pynt,2013,26,4.6,Sanger,12,Premium,One Star,Asia
38,Septime,Paris,France,French Contemporary,1,95,Bertrand Grébaut,2011,28,4.5,Celeriac Toast,14,Fine Dining,One Star,Europe
39,Central,Lima,Peru,Contemporary Peruvian,0,180,Virgilio Martínez,2008,50,4.8,Piranha & Coca,17,Premium,No Stars,South America
40,Maido,Lima,Peru,Nikkei,0,165,Mitsuharu Tsumura,2009,36,4.7,Causa Nikkei,16,Premium,No Stars,South America
41,Pujol,Mexico City,Mexico,Contemporary Mexican,0,155,Enrique Olvera,2000,55,4.7,Mole Madre,25,Premium,No Stars,North America
42,Gaggan Anand,Bangkok,Thailand,Progressive Indian,0,195,Gaggan Anand,2017,14,4.6,Lick It Up,8,Premium,No Stars,Asia
43,Quintonil,Mexico City,Mexico,Contemporary Mexican,0,140,Jorge Vallejo,2012,48,4.6,Esquites,13,Fine Dining,No Stars,North America
44,Sühring,Bangkok,Thailand,Contemporary German,0,185,Thomas & Mathias Sühring,2014,48,4.6,Massaman Curry,11,Premium,No Stars,Asia
45,Boragó,Santiago,Chile,Chilean Contemporary,0,145,Rodolfo Guzmán,2006,40,4.6,Sea Urchin,19,Fine Dining,No Stars,South America
46,Blue Hill at Stone Barns,Pocantico Hills,USA,Farm-to-Table,0,285,Dan Barber,2004,70,4.6,Root Vegetables,21,Luxury,No Stars,North America
47,White Rabbit,Moscow,Russia,Contemporary Russian,0,220,Vladimir Mukhin,2011,50,4.5,King Crab,14,Premium,No Stars,Europe
48,Leo,Bogotá,Colombia,Colombian Contemporary,0,125,Leonor Espinosa,2007,45,4.5,Amazon Ants,18,Fine Dining,No Stars,South America
49,Lyle's,London,UK,British Contemporary,0,85,James Lowe,2014,38,4.5,Pork Chop,11,Fine Dining,No Stars,Europe

In [52]:
df.head()

,Restaurant_Name,City,Country,Cuisine_Type,Michelin_Stars,Average_Price_USD,Chef,Established_Year,Seating_Capacity,Rating,Signature_Dish,Years_Operating,Price_Category,Star_Category,Continent
0,Osteria Francescana,Modena,Italy,Italian Contemporary,3,320,Massimo Bottura,1995,28,4.9,Five Ages of Parmigiano,30,Luxury,Three Stars,Europe
1,Odette,Singapore,Singapore,French Contemporary,3,320,Julien Royer,2008,32,4.9,Hokkaido Sea Urchin,17,Luxury,Three Stars,Asia
2,The French Laundry,Yountville,USA,French,3,390,Thomas Keller,1994,60,4.9,Oysters and Pearls,31,Luxury,Three Stars,North America
3,Arpège,Paris,France,French Vegetarian,3,425,Alain Passard,1986,40,4.9,Heirloom Tomatoes,39,Ultra-Luxury,Three Stars,Europe
4,Mirazur,Menton,France,Mediterranean,3,350,Mauro Colagreco,1991,36,4.8,Salt Crusted Beetroot,34,Luxury,Three Stars,Europe

In [54]:
df.shape

(50, 15)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Restaurant_Name    50 non-null     object
 1   City               50 non-null     object
 2   Country            50 non-null     object
 3   Cuisine_Type       50 non-null     object
 4   Michelin_Stars     50 non-null     int64
 5   Average_Price_USD  50 non-null     int64
 6   Chef               50 non-null     object
 7   Established_Year   50 non-null     int64
 8   Seating_Capacity   50 non-null     int64
 9   Rating             50 non-null     float64
 10  Signature_Dish     50 non-null     object
 11  Years_Operating    50 non-null     int64
 12  Price_Category     50 non-null     object
 13  Star_Category      50 non-null     object
 14  Continent          50 non-null     object
dtypes: float64(1), int64(5), object(9)
memory usage: 6.0+ KB

In [57]:
df.describe()

,Michelin_Stars,Average_Price_USD,Established_Year,Seating_Capacity,Rating,Years_Operating
count,50.000000,50.00000,50.000000,50.00000,50.000000,50.000000
mean,1.920000,281.06000,2001.780000,41.96000,4.702000,23.220000
std,1.192494,103.57811,17.962876,14.69966,0.109712,17.962876
min,0.000000,85.00000,1897.000000,10.00000,4.500000,8.000000
25%,1.000000,212.50000,1998.500000,30.50000,4.600000,14.250000
50%,2.000000,282.50000,2006.500000,45.00000,4.700000,18.500000
75%,3.000000,323.75000,2010.750000,50.00000,4.800000,26.500000
max,3.000000,570.00000,2017.000000,80.00000,4.900000,128.000000

-------------------------------- PART 4 -----------------------------------------

** Handling Missing Values **

In [58]:
import pandas as pd

In [59]:
df2=pd.read_csv(r"C:\Users\Athira\Downloads\archive\market_data.csv")
df2

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [60]:
df2.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [61]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [62]:
df2.isnull() # the null value contain in the cell it shows true othrrwise it shows false

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,False,False,False,False,False,False,False,False,False,False,False,False
8519,False,False,False,False,False,False,False,False,True,False,False,False
8520,False,False,False,False,False,False,False,False,False,False,False,False
8521,False,False,False,False,False,False,False,False,False,False,False,False
8522,False,False,False,False,False,False,False,False,False,False,False,False

In [63]:
df2.isnull().sum()  # calculate the count of the null value column individually

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [64]:
df2.isnull().sum().sum()  # count total number of null values in complete dataframe

np.int64(3873)

** Dropping the rows with nun values **

In [65]:
df2.shape()

TypeError: 'tuple' object is not callable

In [71]:
df2.shape

(8523, 12)

In [68]:
df3=df2.dropna() # drop null value rows and remaining rows is stored in df3 (default axix is 0 remove rows)

In [70]:
df3.shape

(4650, 12)

In [72]:
df3.isnull()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8517,False,False,False,False,False,False,False,False,False,False,False,False
8518,False,False,False,False,False,False,False,False,False,False,False,False
8520,False,False,False,False,False,False,False,False,False,False,False,False
8521,False,False,False,False,False,False,False,False,False,False,False,False
8522,False,False,False,False,False,False,False,False,False,False,False,False

In [73]:
df3.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

** Dropping Columns with null values **

In [74]:
df4=df2.dropna(axis=1)  # remove null value column

In [75]:
df4.shape

(8523, 10)

In [78]:
df2.dropna(how='any')  # remove row any null value contained in data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
...,...,...,...,...,...,...,...,...,...,...,...,...
8517,FDF53,20.750,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [79]:
df2.dropna(how='all') # remove only same row all column contain null

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

---------------------- PART 5 ----------------------------

** filling the null values **

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\archive\market_data.csv")
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [5]:
df.fillna(0)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,0,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [6]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [7]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

In [8]:
df.fillna(0)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,0,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [9]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

In [10]:
df.fillna({'Item_Weight':0})

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [11]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

In [12]:
df['Item_Weight'] = df['Item_Weight'].fillna(0)

In [13]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

In [14]:
df = df.fillna(0)  # remove null value and add zero to that space

In [16]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [19]:
df=df.fillna({'Item_Weight':'none'})

In [20]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [21]:
df = df.fillna({'Item_Weight': 'none'})

In [22]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [23]:
df = df.fillna({'Item_Weight': 'none'})

In [24]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [25]:
df=df.fillna(method='ffill')  # forward fill that means add previous column value to the null value filed

C:\Users\Athira\AppData\Local\Temp\ipykernel_22124\1718901248.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')

In [26]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [27]:
df = df.fillna(method='ffill')
print(df)

     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047
1              DRC01        5.920          Regular         0.019278
2              FDN15       17.500          Low Fat         0.016760
3              FDX07       19.200          Regular         0.000000
4              NCD19        8.930          Low Fat         0.000000
...              ...          ...              ...              ...
8518           FDF22        6.865          Low Fat         0.056783
8519           FDS36        8.380          Regular         0.046982
8520           NCJ29       10.600          Low Fat         0.035186
8521           FDN46        7.210          Regular         0.145221
8522           DRG01       14.800          Low Fat         0.044878

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049
1               Soft Drinks   48.2692            OUT018
2                      Meat  141.6180            OUT049
3     Fruits and Vegetables  182.0950            OUT010
4                 Household   53.8614            OUT013
...                     ...       ...               ...
8518            Snack Foods  214.5218            OUT013
8519           Baking Goods  108.1570            OUT045
8520     Health and Hygiene   85.1224            OUT035
8521            Snack Foods  103.1332            OUT018
8522            Soft Drinks   75.4670            OUT046

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1
1                          2009      Medium               Tier 3
2                          1999      Medium               Tier 1
3                          1998           0               Tier 3
4                          1987        High               Tier 3
...                         ...         ...                  ...
8518                       1987        High               Tier 3
8519                       2002           0               Tier 2
8520                       2004       Small               Tier 2
8521                       2009      Medium               Tier 3
8522                       1997       Small               Tier 1

            Outlet_Type  Item_Outlet_Sales
0     Supermarket Type1          3735.1380
1     Supermarket Type2           443.4228
2     Supermarket Type1          2097.2700
3         Grocery Store           732.3800
4     Supermarket Type1           994.7052
...                 ...                ...
8518  Supermarket Type1          2778.3834
8519  Supermarket Type1           549.2850
8520  Supermarket Type1          1193.1136
8521  Supermarket Type2          1845.5976
8522  Supermarket Type1           765.6700

[8523 rows x 12 columns]

C:\Users\Athira\AppData\Local\Temp\ipykernel_22124\957324947.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

In [28]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [ ]:
df=df.fillna(method='ffill' axis=1) # add previous row value to the null value field

In [29]:
df['Item_Weight'].fillna(value=df['Item_Weight'].mean())

0        9.300
1        5.920
2       17.500
3       19.200
4        8.930
         ...
8518     6.865
8519     8.380
8520    10.600
8521     7.210
8522    14.800
Name: Item_Weight, Length: 8523, dtype: float64

In [30]:
df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,0,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,0.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,0,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,0,Tier 2,Supermarket Type1,4710.5350

In [31]:
df = df.fillna(method='bfill')
print(df)

     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047
1              DRC01        5.920          Regular         0.019278
2              FDN15       17.500          Low Fat         0.016760
3              FDX07       19.200          Regular         0.000000
4              NCD19        8.930          Low Fat         0.000000
...              ...          ...              ...              ...
8518           FDF22        6.865          Low Fat         0.056783
8519           FDS36        8.380          Regular         0.046982
8520           NCJ29       10.600          Low Fat         0.035186
8521           FDN46        7.210          Regular         0.145221
8522           DRG01       14.800          Low Fat         0.044878

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049
1               Soft Drinks   48.2692            OUT018
2                      Meat  141.6180            OUT049
3     Fruits and Vegetables  182.0950            OUT010
4                 Household   53.8614            OUT013
...                     ...       ...               ...
8518            Snack Foods  214.5218            OUT013
8519           Baking Goods  108.1570            OUT045
8520     Health and Hygiene   85.1224            OUT035
8521            Snack Foods  103.1332            OUT018
8522            Soft Drinks   75.4670            OUT046

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                          1999      Medium               Tier 1
1                          2009      Medium               Tier 3
2                          1999      Medium               Tier 1
3                          1998           0               Tier 3
4                          1987        High               Tier 3
...                         ...         ...                  ...
8518                       1987        High               Tier 3
8519                       2002           0               Tier 2
8520                       2004       Small               Tier 2
8521                       2009      Medium               Tier 3
8522                       1997       Small               Tier 1

            Outlet_Type  Item_Outlet_Sales
0     Supermarket Type1          3735.1380
1     Supermarket Type2           443.4228
2     Supermarket Type1          2097.2700
3         Grocery Store           732.3800
4     Supermarket Type1           994.7052
...                 ...                ...
8518  Supermarket Type1          2778.3834
8519  Supermarket Type1           549.2850
8520  Supermarket Type1          1193.1136
8521  Supermarket Type2          1845.5976
8522  Supermarket Type1           765.6700

[8523 rows x 12 columns]

C:\Users\Athira\AppData\Local\Temp\ipykernel_22124\3012849474.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')

---------------------- PART 6 -----------------------------------

** Replace **

In [32]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\sample.csv")
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [33]:
df.replace(to_replace=26,value=30) # replace 26 and add 30 on that space

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      30.0
2          3     89.0       25.0   30.0      27.0
3          4     45.0       30.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        30     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [34]:
df.replace(34,10000) # we can write direct also

    Roll No.  Physics  Chemistry    Maths  Computer
0          1     56.0       57.0     58.0      59.0
1          2     23.0       24.0     25.0      26.0
2          3     89.0       25.0     26.0      27.0
3          4     45.0       26.0     27.0      28.0
4          5     23.0       27.0     28.0      29.0
5          6     90.0        NaN     29.0      30.0
6          7     12.0       13.0     14.0      15.0
7          8     78.0       14.0     15.0      16.0
8          9      NaN       15.0     16.0      17.0
9         10     45.0       16.0     17.0      18.0
10        11      NaN       17.0     18.0      19.0
11        12     88.0        NaN     19.0      20.0
12        13     22.0       23.0     24.0      25.0
13        14     90.0        NaN      NaN      42.0
14        15      NaN       43.0     43.0      43.0
15        16     44.0       44.0     44.0      44.0
16        17     45.0       45.0     45.0      45.0
17        18     46.0       46.0     46.0      46.0
18        19     47.0       47.0     47.0      47.0
19        20     48.0       48.0     48.0      48.0
20        21     49.0       49.0     49.0      49.0
21        22     50.0       50.0     50.0      50.0
22        23     51.0       51.0     51.0      51.0
23        24     52.0       52.0     52.0      52.0
24        25     53.0        NaN      NaN      53.0
25        26     54.0       33.0     33.0      54.0
26        27     55.0    10000.0  10000.0      55.0
27        28     56.0       35.0     35.0       NaN
28        29     57.0       36.0     36.0      66.0
29        30     58.0       37.0     37.0      43.0

In [35]:
df.replace(to_replace=[20,10,30,40,50],value='A') # replace multiple value at a time

   Roll No. Physics Chemistry Maths Computer
0         1    56.0      57.0  58.0     59.0
1         2    23.0      24.0  25.0     26.0
2         3    89.0      25.0  26.0     27.0
3         4    45.0      26.0  27.0     28.0
4         5    23.0      27.0  28.0     29.0
5         6    90.0       NaN  29.0        A
6         7    12.0      13.0  14.0     15.0
7         8    78.0      14.0  15.0     16.0
8         9     NaN      15.0  16.0     17.0
9         A    45.0      16.0  17.0     18.0
10       11     NaN      17.0  18.0     19.0
11       12    88.0       NaN  19.0        A
12       13    22.0      23.0  24.0     25.0
13       14    90.0       NaN   NaN     42.0
14       15     NaN      43.0  43.0     43.0
15       16    44.0      44.0  44.0     44.0
16       17    45.0      45.0  45.0     45.0
17       18    46.0      46.0  46.0     46.0
18       19    47.0      47.0  47.0     47.0
19        A    48.0      48.0  48.0     48.0
20       21    49.0      49.0  49.0     49.0
21       22       A         A     A        A
22       23    51.0      51.0  51.0     51.0
23       24    52.0      52.0  52.0     52.0
24       25    53.0       NaN   NaN     53.0
25       26    54.0      33.0  33.0     54.0
26       27    55.0      34.0  34.0     55.0
27       28    56.0      35.0  35.0      NaN
28       29    57.0      36.0  36.0     66.0
29        A    58.0      37.0  37.0     43.0

In [37]:
df.replace(to_replace=[20,10,30,40,50],value=['A','B','C','D','E'])

   Roll No. Physics Chemistry Maths Computer
0         1    56.0      57.0  58.0     59.0
1         2    23.0      24.0  25.0     26.0
2         3    89.0      25.0  26.0     27.0
3         4    45.0      26.0  27.0     28.0
4         5    23.0      27.0  28.0     29.0
5         6    90.0       NaN  29.0        C
6         7    12.0      13.0  14.0     15.0
7         8    78.0      14.0  15.0     16.0
8         9     NaN      15.0  16.0     17.0
9         B    45.0      16.0  17.0     18.0
10       11     NaN      17.0  18.0     19.0
11       12    88.0       NaN  19.0        A
12       13    22.0      23.0  24.0     25.0
13       14    90.0       NaN   NaN     42.0
14       15     NaN      43.0  43.0     43.0
15       16    44.0      44.0  44.0     44.0
16       17    45.0      45.0  45.0     45.0
17       18    46.0      46.0  46.0     46.0
18       19    47.0      47.0  47.0     47.0
19        A    48.0      48.0  48.0     48.0
20       21    49.0      49.0  49.0     49.0
21       22       E         E     E        E
22       23    51.0      51.0  51.0     51.0
23       24    52.0      52.0  52.0     52.0
24       25    53.0       NaN   NaN     53.0
25       26    54.0      33.0  33.0     54.0
26       27    55.0      34.0  34.0     55.0
27       28    56.0      35.0  35.0      NaN
28       29    57.0      36.0  36.0     66.0
29        C    58.0      37.0  37.0     43.0

In [38]:
df.replace('[A-Za-z]',0,regex=True)

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [40]:
df.replace(to_replace=15,method='ffill')

C:\Users\Athira\AppData\Local\Temp\ipykernel_22124\1094822102.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(to_replace=15,method='ffill')

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      30.0
7          8     78.0       14.0   14.0      16.0
8          9      NaN       14.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        14      NaN       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0        NaN    NaN      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0       NaN
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

------------------------ PART 7 ----------------------------------------

** loc **

In [41]:
import pandas as pd

In [45]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\sample2.csv",index_col=['Roll No.'])
df.head()

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [46]:
df.loc[1]  # get the value of the first location (roll no. 1)

Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 1, dtype: object

In [47]:
df.loc[5]

Section               A
Branch               CS
Physics            23.0
Chemistry          27.0
Maths              28.0
Computer           29.0
DOB          05-01-2001
Name: 5, dtype: object

In [48]:
df.loc[[4,5,6,7]] # to print array of values

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001
6              A    ECE     90.0        NaN   29.0      30.0  06-01-2001
7              B     CS     12.0       13.0   14.0      15.0  07-01-2001

In [49]:
df.loc[5,'Physics']

np.float64(23.0)

In [50]:
df.loc[6:15,"Chemistry"]

Roll No.
6      NaN
7     13.0
8     14.0
9     15.0
10    16.0
11    17.0
12     NaN
13    23.0
14     NaN
15    43.0
Name: Chemistry, dtype: float64

In [51]:
df.loc[df['Physics']>50]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
6              A    ECE     90.0        NaN   29.0      30.0  06-01-2001
8              C    NaN     78.0       14.0   15.0      16.0  08-01-2001
12             C     CS     88.0        NaN   19.0      20.0  12-01-2001
14             A     CS     90.0        NaN    NaN      42.0  14-01-2001
23             B    ECE     51.0       51.0   51.0      51.0  23-01-2001
24             C   MECH     52.0       52.0   52.0      52.0  24-01-2001
25             A   MECH     53.0        NaN    NaN      53.0  25-01-2001
26             A    ECE     54.0       33.0   33.0      54.0  26-01-2001
27             B     CS     55.0       34.0   34.0      55.0  27-01-2001
28             C     CS     56.0       35.0   35.0       NaN  28-01-2001
29             A     CS     57.0       36.0   36.0      66.0  29-01-2001
30             A     CS     58.0       37.0   37.0      43.0  30-01-2001

In [52]:
df.loc[df['Chemistry']>80]

Empty DataFrame
Columns: [Section, Branch, Physics, Chemistry, Maths, Computer, DOB]
Index: []

In [54]:
df.loc[df['Physics']>80,['Maths']] # print only maths that is only 80% greater than physics

          Maths
Roll No.
3          26.0
6          29.0
12         19.0
14          NaN

** iloc **

In [55]:
df.iloc[0] # it consider the index number base not roll no

Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 1, dtype: object

In [56]:
 df.iloc[[1]]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001

In [57]:
 df.iloc[[0,1,2,3]]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001

In [58]:
df.iloc[:,2]

Roll No.
1     56.0
2     23.0
3     89.0
4     45.0
5     23.0
6     90.0
7     12.0
8     78.0
9      NaN
10    45.0
11     NaN
12    88.0
13    22.0
14    90.0
15     NaN
16    44.0
17    45.0
18    46.0
19    47.0
20    48.0
21    49.0
22    50.0
23    51.0
24    52.0
25    53.0
26    54.0
27    55.0
28    56.0
29    57.0
30    58.0
Name: Physics, dtype: float64

In [59]:
df.iloc[0:5,2] # print o to 5 value print 2nd column

Roll No.
1    56.0
2    23.0
3    89.0
4    45.0
5    23.0
Name: Physics, dtype: float64

In [60]:
df.iloc[0:5,2:4]

          Physics  Chemistry
Roll No.
1            56.0       57.0
2            23.0       24.0
3            89.0       25.0
4            45.0       26.0
5            23.0       27.0

--------------------------- PART 8 ------------------------------------

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\sample2.csv")
df.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

** GroupBy() Function **

In [7]:
branch_group=df.groupby(by="Branch")
branch_group                           # we are grouping the data in the basis of branch that is more easier to idetify the persons

In [8]:
branch_group.groups

{'CS': [0, 4, 6, 9, 11, 12, 13, 26, 27, 28, 29], 'ECE': [1, 5, 8, 10, 14, 18, 22, 25], 'MECH': [2, 3, 16, 17, 19, 20, 21, 23, 24]}

groupby() in pandas is used to group rows based on one or more columns and then perform aggregations such as sum(), mean(), count(), etc.

In [13]:
branch_group=df.groupby(by=["Branch","Section"])

In [15]:
branch_group.groups

{('CS', 'A'): [0, 4, 9, 12, 13, 28, 29], ('CS', 'B'): [6, 26], ('CS', 'C'): [11, 27], ('ECE', 'A'): [1, 5, 8, 25], ('ECE', 'B'): [10, 14, 18, 22], ('MECH', 'A'): [16, 17, 20, 21, 24], ('MECH', 'B'): [2], ('MECH', 'C'): [3, 19, 23], (nan, 'C'): [7, 15]}

In [16]:
for group,data_frame in branch_group:
    print(group)
    print(data_frame)

('CS', 'A')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0          1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
4          5       A     CS     23.0       27.0   28.0      29.0  05-01-2001
9         10       A     CS     45.0       16.0   17.0      18.0  10-01-2001
12        13       A     CS     22.0       23.0   24.0      25.0  13-01-2001
13        14       A     CS     90.0        NaN    NaN      42.0  14-01-2001
28        29       A     CS     57.0       36.0   36.0      66.0  29-01-2001
29        30       A     CS     58.0       37.0   37.0      43.0  30-01-2001
('CS', 'B')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
6          7       B     CS     12.0       13.0   14.0      15.0  07-01-2001
26        27       B     CS     55.0       34.0   34.0      55.0  27-01-2001
('CS', 'C')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
11        12       C     CS     88.0        NaN   19.0      20.0  12-01-2001
27        28       C     CS     56.0       35.0   35.0       NaN  28-01-2001
('ECE', 'A')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
1          2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
5          6       A    ECE     90.0        NaN   29.0      30.0  06-01-2001
8          9       A    ECE      NaN       15.0   16.0      17.0  09-01-2001
25        26       A    ECE     54.0       33.0   33.0      54.0  26-01-2001
('ECE', 'B')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
10        11       B    ECE      NaN       17.0   18.0      19.0  11-01-2001
14        15       B    ECE      NaN       43.0   43.0      43.0  15-01-2001
18        19       B    ECE     47.0       47.0   47.0      47.0  19-01-2001
22        23       B    ECE     51.0       51.0   51.0      51.0  23-01-2001
('MECH', 'A')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
16        17       A   MECH     45.0       45.0   45.0      45.0  17-01-2001
17        18       A   MECH     46.0       46.0   46.0      46.0  18-01-2001
20        21       A   MECH     49.0       49.0   49.0      49.0  21-01-2001
21        22       A   MECH     50.0       50.0   50.0      50.0  22-01-2001
24        25       A   MECH     53.0        NaN    NaN      53.0  25-01-2001
('MECH', 'B')
   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
('MECH', 'C')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
3          4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
19        20       C   MECH     48.0       48.0   48.0      48.0  20-01-2001
23        24       C   MECH     52.0       52.0   52.0      52.0  24-01-2001

** Merge() Function **

In [ ]:
create two data frame df1 and df2 then it merge in one frame

In [18]:
df1=pd.DataFrame({'Roll No':[1,2,3,4],'Physics':[34,56,78,39]})
df1

   Roll No  Physics
0        1       34
1        2       56
2        3       78
3        4       39

In [20]:
df2=pd.DataFrame({'Roll No':[1,2,3,4],'Chemistry':[34,56,78,39]})
df2

   Roll No  Chemistry
0        1         34
1        2         56
2        3         78
3        4         39

In [22]:
pd.merge(df1,df2, on='Roll No')

   Roll No  Chemistry_x  Chemistry_y
0        1           34           34
1        2           56           56
2        3           78           78
3        4           39           39

In [23]:
df1=pd.DataFrame({'Roll No':[1,2,3,4],'Economics':[34,56,78,39]})
df1

   Roll No  Economics
0        1         34
1        2         56
2        3         78
3        4         39

In [24]:
df2=pd.DataFrame({'Roll No':[1,2,3,4],'History':[34,56,78,39]})
df2

   Roll No  History
0        1       34
1        2       56
2        3       78
3        4       39

In [25]:
pd.merge(df1,df2, on='Roll No')

   Roll No  Economics  History
0        1         34       34
1        2         56       56
2        3         78       78
3        4         39       39

In [26]:
pd.merge(df1,df2)  # only display intersection

   Roll No  Economics  History
0        1         34       34
1        2         56       56
2        3         78       78
3        4         39       39

In [27]:
df3=pd.DataFrame({'Roll No':[1,2,3,4,5],'Economics':[34,56,78,39,67]})
df4=pd.DataFrame({'Roll No':[1,2,3,6,7],'History':[34,56,78,39,49]})

In [28]:
pd.merge(df3,df4)  # only display two common roll no

   Roll No  Economics  History
0        1         34       34
1        2         56       56
2        3         78       78

In [29]:
pd.merge(df3,df4, how='left')   # left merge

   Roll No  Economics  History
0        1         34     34.0
1        2         56     56.0
2        3         78     78.0
3        4         39      NaN
4        5         67      NaN

In [30]:
pd.merge(df3,df4, how='right') # right merge

   Roll No  Economics  History
0        1       34.0       34
1        2       56.0       56
2        3       78.0       78
3        6        NaN       39
4        7        NaN       49

In [31]:
pd.merge(df3,df4, how='outer') # full join

   Roll No  Economics  History
0        1       34.0     34.0
1        2       56.0     56.0
2        3       78.0     78.0
3        4       39.0      NaN
4        5       67.0      NaN
5        6        NaN     39.0
6        7        NaN     49.0

---------------------------------- PART 9 --------------------------------

** append function **

In [32]:
import pandas as pd

In [34]:
df1=pd.DataFrame({'Roll No':[1,2,3,4,5],'Physics':[45,56,34,56,67],'Maths':[45,34,56,78,56]})
df2=pd.DataFrame({'Roll No':[6,7,8,9,10],'Physics':[47,56,34,53,62],'Maths':[40,30,56,78,52]})
print(df1)
print(df2)

   Roll No  Physics  Maths
0        1       45     45
1        2       56     34
2        3       34     56
3        4       56     78
4        5       67     56
   Roll No  Physics  Maths
0        6       47     40
1        7       56     30
2        8       34     56
3        9       53     78
4       10       62     52

In [36]:
pd.concat([df1, df2])

   Roll No  Physics  Maths
0        1       45     45
1        2       56     34
2        3       34     56
3        4       56     78
4        5       67     56
0        6       47     40
1        7       56     30
2        8       34     56
3        9       53     78
4       10       62     52

In [37]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)                                      # ignore index

   Roll No  Physics  Maths
0        1       45     45
1        2       56     34
2        3       34     56
3        4       56     78
4        5       67     56
5        6       47     40
6        7       56     30
7        8       34     56
8        9       53     78
9       10       62     52

In [38]:
result = pd.concat([df1, df2], ignore_index=True, sort=True)
print(result)                                                  # sort column name

   Maths  Physics  Roll No
0     45       45        1
1     34       56        2
2     56       34        3
3     78       56        4
4     56       67        5
5     40       47        6
6     30       56        7
7     56       34        8
8     78       53        9
9     52       62       10

------------------------------------- PART 10 -----------------------------

In [39]:
import pandas as pd

In [40]:
df=pd.read_csv(r"C:\Users\Athira\Downloads\sample2.csv")
df.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

** Pivot Table **

In [44]:
print(df.dtypes)

Roll No.       int64
Section       object
Branch        object
Physics      float64
Chemistry    float64
Maths        float64
Computer     float64
DOB           object
dtype: object

In [48]:
pd.pivot_table(df,index='Branch',aggfunc='count')

        Chemistry  Computer  DOB  Maths  Physics  Roll No.  Section
Branch
CS              9        10   11     10       11        11       11
ECE             7         8    8      8        5         8        8
MECH            8         9    9      8        9         9        9

In [49]:
pd.pivot_table(df,index='Branch',aggfunc='sum')

,Chemistry,Computer,DOB,Maths,Physics,Roll No.,Section
Branch,,,,,,,
CS,278.0,372.0,01-01-200105-01-200107-01-200110-01-200112-01-...,302.0,562.0,176,AABACAABCAA
ECE,230.0,287.0,02-01-200106-01-200109-01-200111-01-200115-01-...,262.0,265.0,111,AAABBBBA
MECH,341.0,398.0,03-01-200104-01-200117-01-200118-01-200120-01-...,343.0,477.0,154,BCAACAACA

In [50]:
pd.pivot_table(df,index='Branch',aggfunc='max')

        Chemistry  Computer         DOB  Maths  Physics  Roll No. Section
Branch
CS           57.0      66.0  30-01-2001   58.0     90.0        30       C
ECE          51.0      54.0  26-01-2001   51.0     90.0        26       B
MECH         52.0      53.0  25-01-2001   52.0     89.0        25       C

In [55]:
pd.pivot_table(df,index='Branch',columns='Section',aggfunc='count')

        Chemistry           Computer            DOB           Maths            \
Section         A    B    C        A    B    C    A    B    C     A    B    C
Branch
CS            6.0  2.0  1.0      7.0  2.0  1.0  7.0  2.0  2.0   6.0  2.0  2.0
ECE           3.0  4.0  NaN      4.0  4.0  NaN  4.0  4.0  NaN   4.0  4.0  NaN
MECH          4.0  1.0  3.0      5.0  1.0  3.0  5.0  1.0  3.0   4.0  1.0  3.0

        Physics           Roll No.
Section       A    B    C        A    B    C
Branch
CS          7.0  2.0  2.0      7.0  2.0  2.0
ECE         3.0  2.0  NaN      4.0  4.0  NaN
MECH        5.0  1.0  3.0      5.0  1.0  3.0